const cities = [
    "Abbeville",
    "Acworth",
    "Adairsville",
    "Adel",
    "Adrian",
    "Ailey",
    "Alamo",
    "Albany",
    "Aldora",
    "Allenhurst",
    "Allentown",
    "Alma",
    "Alpharetta",
    "Alston",
    "Alto",
    "Ambrose",
    "Americus",
    "Andersonville",
    "Arabi",
    "Aragon",
    "Arcade",
    "Argyle",
    "Arlington",
    "Arnoldsville",
    "Ashburn",
    "Athens",
    "Atlanta",
    "Attapulgus",
    "Auburn",
    "Augusta",
    "Austell",
    "Avalon",
    "Avera",
    "Avondale Estates",
    "Axson",
    "Baconton",
    "Bainbridge",
    "Baldwin",
    "Ball Ground",
    "Barnesville",
    "Bartow",
    "Barwick",
    "Baxley",
    "Bellville",
    "Berkeley Lake",
    "Berlin",
    "Bethlehem",
    "Between",
    "Bishop",
    "Blackshear",
    "Blairsville",
    "Blakely",
    "Bloomingdale",
    "Blue Ridge",
    "Bluffton",
    "Blythe",
    "Bogart",
    "Bonaire",
    "Boston",
    "Bostwick",
    "Bowdon",
    "Bowdon Junction",
    "Bowersville",
    "Bowman",
    "Braselton",
    "Braswell",
    "Bremen",
    "Brinson",
    "Bristol",
    "Bronwood",
    "Brooklet",
    "Brooks",
    "Broxton",
    "Brunswick",
    "Buchanan",
    "Buckhead",
    "Buena Vista",
    "Buford",
    "Butler",
    "Byromville",
    "Cadwell",
    "Cairo",
    "Calhoun",
    "Camak",
    "Camilla",
    "Canon",
    "Canton",
    "Carl",
    "Carlton",
    "Carnesville",
    "Carrollton",
    "Cartersville",
    "Cave Spring",
    "Cecil",
    "Cedartown",
    "Centerville",
    "Centralhatchee",
    "Chamblee",
    "Chatsworth",
    "Chauncey",
    "Chester",
    "Chickamauga",
    "Clarkesville",
    "Clarkston",
    "Claxton",
    "Clayton",
    "Clermont",
    "Cleveland",
    "Climax",
    "Cobbtown",
    "Cochran",
    "Cohutta",
    "Colbert",
    "Coleman",
    "College Park",
    "Collins",
    "Colquitt",
    "Columbus",
    "Comer",
    "Commerce",
    "Concord",
    "Conyers",
    "Coolidge",
    "Cordele",
    "Cornelia",
    "Covington",
    "Crawford",
    "Crawfordville",
    "Culloden",
    "Cumming",
    "Cusseta",
    "Cuthbert",
    "Dacula",
    "Dahlonega",
    "Dallas",
    "Dalton",
    "Damascus",
    "Danville",
    "Darien",
    "Dasher",
    "Dawson",
    "Dawsonville",
    "Dearing",
    "Decatur",
    "Demorest",
    "Denton",
    "De Soto",
    "Dexter",
    "Dillard",
    "Doerun",
    "Donalsonville",
    "Doraville",
    "Douglas",
    "Douglasville",
    "Du Pont",
    "Dudley",
    "Duluth",
    "Duncanville",
    "Dunsmore",
    "East Dublin",
    "East Ellijay",
    "East Point",
    "Eastman",
    "Eatonton",
    "Edge Hill",
    "Edison",
    "Elberton",
    "Ellaville",
    "Ellenton",
    "Ellijay",
    "Emerson",
    "Enigma",
    "Ephesus",
    "Eton",
    "Evans",
    "Fairburn",
    "Fairmount",
    "Fargo",
    "Fayetteville",
    "Fitzgerald",
    "Flemington",
    "Flovilla",
    "Flowery Branch",
    "Folkston",
    "Forest Park",
    "Forsyth",
    "Fort Gaines",
    "Fort Oglethorpe",
    "Fort Valley",
    "Franklin",
    "Franklin Springs",
    "Funston",
    "Gainesville",
    "Garden City",
    "Garfield",
    "Gay",
    "Georgetown",
    "Gibson",
    "Gillsville",
    "Girard",
    "Glennville",
    "Glenwood",
    "Good Hope",
    "Gordon",
    "Gracewood",
    "Grantville",
    "Gray",
    "Grayson",
    "Greensboro",
    "Greenville",
    "Greshamville",
    "Griffin",
    "Grovetown",
    "Gumbranch",
    "Guyton",
    "Hagan",
    "Hahira",
    "Hamilton",
    "Hampton",
    "Hapeville",
    "Harlem",
    "Harrison",
    "Hartford",
    "Hartwell",
    "Hawkinsville",
    "Hazlehurst",
    "Helen",
    "Helena",
    "Hephzibah",
    "Hiawassee",
    "Higgston",
    "Hilltop",
    "Hiltonia",
    "Hinesville",
    "Hiram",
    "Hoboken",
    "Hogansville",
    "Holly Springs",
    "Homeland",
    "Homer",
    "Homerville",
    "Hoschton",
    "Hull",
    "Ideal",
    "Ila",
    "Indian Springs",
    "Iron City",
    "Irwinton",
    "Isabella",
    "Isle of Hope",
    "Ivey",
    "Jackson",
    "Jacksonville",
    "Jakin",
    "Jasper",
    "Jefferson",
    "Jeffersonville",
    "Jenkinsburg",
    "Jersey",
    "Jesup",
    "Jonesboro",
    "Junction City",
    "Kennesaw",
    "Keysville",
    "Kingsland",
    "Kingston",
    "Kite",
    "LaFayette",
    "LaGrange",
    "Lake City",
    "Lake Park",
    "Lakeland",
    "Lavonia",
    "Lawrenceville",
    "Leary",
    "Leesburg",
    "Lenox",
    "Leslie",
    "Lexington",
    "Lilburn",
    "Lilly",
    "Lincolnton",
    "Lithia Springs",
    "Lithonia",
    "Locust Grove",
    "Loganville",
    "Lookout Mountain",
    "Louisville",
    "Lovejoy",
    "Ludowici",
    "Lula",
    "Lumber City",
    "Lumpkin",
    "Luthersville",
    "Lyerly",
    "Lyons",
    "Mableton",
    "McCaysville",
    "McDonough",
    "McIntyre",
    "McRae-Helena",
    "Madison",
    "Manassas",
    "Manchester",
    "Mansfield",
    "Marietta",
    "Marshallville",
    "Martin",
    "Maxeys",
    "Maysville",
    "Meansville",
    "Meigs",
    "Menlo",
    "Metter",
    "Midville",
    "Midway",
    "Milan",
    "Milledgeville",
    "Millen",
    "Millwood",
    "Milton",
    "Mitchell",
    "Molena",
    "Monroe",
    "Montezuma",
    "Monticello",
    "Montrose",
    "Moreland",
    "Morgan",
    "Morganton",
    "Morrow",
    "Morven",
    "Moultrie",
    "Mount Airy",
    "Mount Vernon",
    "Mount Zion",
    "Mountain City",
    "Mountain Park",
    "Murrayville",
    "Musella",
    "Nahunta",
    "Nashville",
    "Newborn",
    "Newington",
    "Newnan",
    "Newton",
    "Nicholls",
    "Nicholson",
    "Norcross",
    "Norman Park",
    "Norwood",
    "Nunez",
    "Oak Park",
    "Oakwood",
    "Ochlocknee",
    "Ocilla",
    "Oconee",
    "Odum",
    "Offerman",
    "Oglethorpe",
    "Oliver",
    "Omega",
    "Oxford",
    "Palmetto",
    "Parrott",
    "Patterson",
    "Pavo",
    "Peachtree City",
    "Pearson",
    "Pelham",
    "Pembroke",
    "Pendergrass",
    "Perry",
    "Phillipsburg",
    "Pine Lake",
    "Pine Mountain",
    "Pinehurst",
    "Pineview",
    "Pitts",
    "Plains",
    "Plainville",
    "Pooler",
    "Portal",
    "Porterdale",
    "Poulan",
    "Powder Springs",
    "Preston",
    "Pulaski",
    "Putney",
    "Quitman",
    "Ray City",
    "Rayle",
    "Rebecca",
    "Redan",
    "Register",
    "Reidsville",
    "Remerton",
    "Rentz",
    "Resaca",
    "Rest Haven",
    "Reynolds",
    "Rhine",
    "Riceboro",
    "Richland",
    "Richmond Hill",
    "Riddleville",
    "Rincon",
    "Ringgold",
    "Riverdale",
    "Riverside",
    "Roberta",
    "Rochelle",
    "Rockmart",
    "Rocky Ford",
    "Rome",
    "Roopville",
    "Rossville",
    "Roswell",
    "Royston",
    "Rutledge",
    "Sale City",
    "Sandersville",
    "Sandy Springs",
    "Sardis",
    "Sargent",
    "Sasser",
    "Savannah",
    "Scotland",
    "Screven",
    "Senoia",
    "Sharon",
    "Sharpsburg",
    "Shellman",
    "Shiloh",
    "Siloam",
    "Sky Valley",
    "Smithville",
    "Smyrna",
    "Snellville",
    "Social Circle",
    "Soperton",
    "Sparks",
    "Sparta",
    "Springfield",
    "Stapleton",
    "Statenville",
    "Statesboro",
    "Statham",
    "Stillmore",
    "Stockbridge",
    "Stone Mountain",
    "Sugar Hill",
    "Summerville",
    "Sumner",
    "Sunny Side",
    "Surrency",
    "Suwanee",
    "Swainsboro",
    "Sycamore",
    "Sylvania",
    "Sylvester",
    "Tallapoosa",
    "Talmo",
    "Tarrytown",
    "Taylorsville",
    "Temple",
    "Tennille",
    "Thomaston",
    "Thomasville",
    "Thomson",
    "Thunderbolt",
    "Tifton",
    "Tiger",
    "Tignall",
    "Toccoa",
    "Toomsboro",
    "Trenton",
    "Trion",
    "Tucker",
    "Tunnel Hill",
    "Turin",
    "Twin City",
    "Tybee Island",
    "Tyrone",
    "Unadilla",
    "Union City",
    "Union Point",
    "Uvalda",
    "Valdosta",
    "Varnell",
    "Vernonburg",
    "Vidalia",
    "Vidette",
    "Vienna",
    "Villa Rica",
    "Waco",
    "Wadley",
    "Waleska",
    "Walnut Grove",
    "Walthourville",
    "Warm Springs",
    "Warner Robins",
    "Warrenton",
    "Warwick",
    "Washington",
    "Watkinsville",
    "Waverly Hall",
    "Waycross",
    "Waynesboro",
    "West Point",
    "Whigham",
    "White",
    "White Plains",
    "Whitesburg",
    "Willacoochee",
    "Williamson",
    "Winder",
    "Winterville",
    "Woodbine",
    "Woodbury",
    "Woodland",
    "Woodstock",
    "Woolsey",
    "Wrens",
    "Wrightsville",
    "Yatesville",
    "Young Harris",
    "Zebulon"
  ];
export default cities;